### ISSUE TITLE
Moving line with the table

### ISSUE THREAD

**Issue by ricardouriegas** [ricardouriegas/sql-developer-and-modeler#2]
The line that represent a relationship should move with the `Start Table` or the `End Table`, with this i mean it should be able of move the end or start of the line depending on the table's move.

**Comment by ricardouriegas** [comment]
is mid solved; with this i mean it works only with one side of the relation, you can find it on `uriegas_branch`, the solution should be separate the relation in  the table on 2.
- 1 list of relations it point to (this means that the actual table point to another table)
- 1 list of relations another table points to it (this means another table point to the actual table)

**Comment by EliasHdzR** [comment]
Separate the relation in two list wasn't needed, the next lines of code fixed the issue:
```
// update the position of every relationship
        for(Relation relation : foreignKeys){
            if(relation.getStartTable() == this){
                // update the line that connects to the table
                relation.setStartX(relation.getStartX() + deltaX);
                relation.setStartY(relation.getStartY() + deltaY);
            }

            if(relation.getEndTable() == this){
                relation.setEndX(relation.getEndX() + deltaX);
                relation.setEndY(relation.getEndY() + deltaY);
            }
        }
```
